### ISSUE TITLE
Implement **variables** in the **TailoredProfile** object.

### ISSUE THREAD

**Issue by JAORMX** [JAORMX/compliance-profile-operator#3]
**TailoredProfiles** are able to select and deselect rules for a specific profile. However, they should also be able to set certain variables (through the `variables` key):

e.g.

```
kind: TailoredProfile
apiVersion: compliance.openshift.io/v1alpha1
metadata:
  name: ocp4-moderate-custom
spec:
  extends: ocp4-moderate
  title: | 
    NIST 800-53 Moderate-Impact Baseline for Red Hat Enterprise Linux
    CoreOS customized for this deployment
  description: |
    This compliance profile reflects the core set of Moderate-Impact
    Baseline configuration settings for deployment of Red Hat
    Enterprise
    …
  enableRules:
    - ruleName: chronyd_client_only
      rationale: We really need to enable this
  disableRules:
    - ruleName: chronyd_no_chronyc_network
      rationale: This doesn’t apply to my cluster
  variables:
    - var_password_pam_difok: 5
status:
  id: xccdf_org.ssgproject.content_profile_ocp4-moderate-custom
  tailoringConfigMap:
    name: ocp4-moderate-custom
    namespace: this-namespace
```

Here, the variable `var_password_pam_difok` is set to 5.

Note that preferably this should refer to a Variable Custom Resource that would expose the acceptable values.
